include_subgraph_errors:
  all: true
rhai:
  scripts: "./router-scripts"
  main: "main.rhai"
sandbox:
  enabled: true
homepage:
  enabled: false
supergraph:
  introspection: true
coprocessor:
  url: http://127.0.0.1:8081/
  timeout: 20s
  supergraph:
    request:
      headers: true
      body: true
      context: true
      sdl: true
      method: false
    response: # By including this key, the `RouterService` sends a coprocessor request whenever it's about to send response data to a client (including incremental data via @defer).
      headers: true
      body: true
      context: true
      sdl: false
      status_code: true
  router:
    response:
      headers: true
      body: true
      context: true
      sdl: true
      status_code: true
authentication:
  router:
    jwt:
      jwks:
        - url: https://dev-ehypgoyowlqgztgd.us.auth0.com/.well-known/jwks.json
